Handout Containerisation/Binder
Geosoft2/geosoft2-2020 pull request #17
Opened 2020-10-21 10:01 UTC by Leg-en

2020-10-21 14:05 UTC, nuest commented
@Leg-en Ist das hier noch "work on progress" oder hättest du gerne Feedback?

2020-10-21 16:44 UTC, Leg-en commented
Gerne Feedback, vor allem inhaltlich. Ich arbeite überarbeite noch Details wie Rechtschreibung etc

2020-10-22 14:53 UTC, nuest requested changes
- Welche Alternativen zu Docker gibt es?
- Bitte zu `docker-compose` mit @Svub1 absprechen und bitte auch mal ausprobieren!
- Kubernetes erwähnen, aber keine Beispiele/Ausprobieren nötig.

Insgesamt fehlen mir noch etwas _deine_ Erfahrungen - das sieht noch ziemlich zusammenkopiert aus. Wichtig ist dass du dich auskennst und _gut_ Tutorials/Seiten/Quellen verlinkst bzw. Inhalte zusammenfasst, aber auch dass du praktische Erfahrungen machst und mit den anderen teilen kannst.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +Quellen:
Für den Leser ist es deutlich hilfreicher, wenn die Links dem entsprechenden Inhalt zugeordnet sind und nicht am Ende.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +-   <a href="https://www.docker.com/resources/what-container" class="uri">https://www.docker.com/resources/what-container</a>
Markdown-Formatierung erhöht die Lesbarkeit im plain text Modus.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +    umwandelt
Klar machen, was das image dann kann - es ist ja speziell erstellt für die Nutzung über Jupyter.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +-   Frei downloadbar und anwendbar
Bitte auch mal ausprobieren, also `repo2docker` lokal installieren und auf einem Ordner ausführen.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +### Docker rm
Überschrift passt nicht zum Inhalt.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +### Docker Run
Optionen `-i` und `-t` sind ebenfalls noch sehr wichtig.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +-   Alternativ: Über Docker Desktop Starten
Beispiele ergänzen oder auf Beispiele verweisen.

2020-10-22 14:53 UTC, nuest commented on Containerisation/Containerisation.md
> +-   Container sind in der Regel wenige Megabyte groß
Das ist nicht korrekt - R-basierte container mit nennenswertem Funktionsumfang sind schnell 1GB und größer.

Bitte mal verschiedene Images pullen und ausprobieren. `docker images` liefert ja auch die Größe.

2020-10-28 19:00 UTC, Leg-en commented
Danke fürs  Feedback. Hab versucht, alles umzusetzen. Habe Docker Alternativen hinzugefügt, jedoch sehr kurz gehalten, da mir das nur begrenz wichtig erschien. Habe mich mit @Svub1 abgesprochen und Docker Compose angerissen. Ein näheres drauf eingehen würde sonst zu Überschneidungen mit seiner Abgabe führen. Kubierendes hinzugefügt. Dabei hatte ich aber Verständnis Probleme. Wenn das so nicht korrekt ist, würde ich mich über Hilfe freuen. 

Ansonsten habe ich die markdown Formatierung für Links verwendet und Quellen direkt zugeordnet. Repo2docker einmal ausprobiert und Wichtiges ergänzt. Ebenso habe ich die geforderten Beispiele und Parameter ergänzt. Ebenso habe ich ergänzt, dass es größere Packages geben kann, das jedoch nicht so oft vorkommt. 

Würde mich über weiteres Feedback freuen. @nuest

2020-11-03 11:27 UTC, nuest reviewed
Sieht gut aus - Danke für das Update.

Hast du Kubernetes auch mal ausprobiert?

Ansonsten warten wir ab, ob es noch Nachfragen beim Vortrag gibt die hier geupdated werden müssten, dann mergen wir.

2020-11-19 13:52 UTC, merged