Micro-Services_Handout
Geosoft2/geosoft2-2020 pull request #18
Opened 2020-10-21 10:04 UTC by Svub1

2020-10-21 14:05 UTC, nuest commented
@Svub1 Ist das noch work in progress, oder hättest du gerne Feedback?

2020-10-21 14:30 UTC, Svub1 commented
Ein Feedback wäre nett, dann könnte ich das Handout gegebenenfalls nächste Woche noch verbessern. Vielen Dank schon mal im Voraus!

2020-10-22 15:04 UTC, nuest requested changes
Guter erster Aufschlag vom Inhalt her, aber es fehlen noch deine praktischen Erfahrungen. Bitte auch davon berichten!

2020-10-22 15:04 UTC, nuest commented on Mirco-Services/Mikro_Services.md
> +
Aus meiner Sicht fehlt noch: _ein_ Entwickler oder ein kleines Team kann vollkommen _verantwortlich_ sein für die Entwicklung/Testen/Betrieb. Bitte in der Richtung nochmal recherchieren.

2020-10-22 15:04 UTC, nuest commented on Mirco-Services/Mikro_Services.md
> +-   [Overview of Docker Compose](https://docs.docker.com/compose/)
Links bei den jeweiligen Inhalten sind für den Leser viel komfortabler - bitte eindeutig zuordnen, so wenig hilfreich.

2020-10-22 15:04 UTC, nuest commented on Mirco-Services/Mikro_Services.md
> +Reverse-Proxy
Bitte hier auf jeden Fall praktisch ausprobieren, z.B. mit nginx und mehreren Containern in einer `docker-compose.yml`. Beispiele sollte es viele geben, sonst gerne melden.

2020-10-22 15:04 UTC, nuest commented on Mirco-Services/Mikro_Services.md
> +Anwendungsgebiete von Reverse Proxy
Bitte noch um kurze Info zu CORS ergänzen und am besten direkt in das praktische Beispiel einbauen.

2020-10-22 15:04 UTC, nuest commented on Mirco-Services/Mikro_Services.md
> +Anwendungsgebiete von Reverse Proxy
Für diese Punkt (load balancing, caching, compression) sollte es auch jeweils Tutorials/Beispiele geben wir das mit docker-compose, nginx und Python (oder anderen Sprachen) umsetzbar ist. Bitte ausprobieren und verlinken.

2020-10-22 15:11 UTC, Svub1 commented on Mirco-Services/Mikro_Services.md
> +Anwendungsgebiete von Reverse Proxy
Vielen Dank für dein erstes Feedback.

2020-10-22 15:13 UTC, Svub1 commented
Vielen Dank für dein Feedback

2020-10-29 10:34 UTC, Svub1 commented
@nuest ich habe die Nachteile von Microservices ergänzt, die Quellen verbessert und CORS hinzugefügt. Allerdings fehlt mir noch ein Beispiel zu nginx. Könntest du mir das eins nennen?  Und evtl. nocheinmal kurz über die ergänzten Punkte sehen? Vielen Dank Sven

2020-10-30 15:11 UTC, nuest commented
nginx - Beispiel: https://duckduckgo.com/?t=canonical&q=nginx+reverse+proxy+docker-compose&ia=web

Die ersten Treffer gehen alle in die richtige Richtung, außer alles mit Zertifikaten - das ist erstmal nicht so wichtig.

Vielleicht https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg und https://dzone.com/articles/how-to-nginx-reverse-proxy-with-docker-compose

2020-11-19 14:15 UTC, nuest commented
@Svub1 Bitte nach dem öffnen eines pull requets nochmal prüfen welche Dateien du geändert hast. Warum war die `README.md` gelöscht?

2020-11-19 14:15 UTC, merged