Handout STAC
Geosoft2/geosoft2-2020 pull request #20
Opened 2020-10-26 23:54 UTC by digilog11

@digilog11
Bereit für Feedback

2020-10-29 14:49 UTC, nuest requested changes
Danke - sieht schon recht gut aus!

@m-mohr Könntest du nochmal drüber schauen ob was wichtiges fehlt, das die Teilnehmer von Geosoft II wissen sollten?

2020-10-29 14:49 UTC, nuest commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +#### API Filter
Beispiele sind gut - könntest du bitte dann auch die Ergebnisse ergänzen? Oder die Links einfach anklickbar machen?

2020-10-29 14:49 UTC, nuest commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +#### API Filter
Vielleicht als screenshot oder auch nur eine teilweise Antwort (sonst könnte es etwas lang werden).

2020-10-29 14:49 UTC, nuest commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +## Gründe für die Entwicklung von STAC
Vielleicht findet ihr hier noch Inhalte wo STAC gegenüber den "alten" Standards des OGC abgegrenzt wird. Warum sind CSW, W(C)PS nicht geeignet? Wie verhält STAC sich zu anderen Standards?

Finde ich wichtig, weil die OGC-Dienste ggf. im Team bekannter sind.

2020-10-29 14:49 UTC, nuest commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +[Weitere Beispiele](https://github.com/radiantearth/stac-api-spec/blob/master/examples.md)
Gibt es auch Software Bibliotheken um mit einer STAC-Instanz zu kommunizieren (Python, R) ?

2020-10-29 15:14 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +STAC ist eine Sprache zur Beschreibung von räumlichen Katalogen und Assets. Der Fokus liegt auf die Suche und Entdeckung von Daten.
Zeit spielt auch eine wichtige Rolle => raumzeitliche Kataloge

2020-10-29 15:17 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +Mit „Spatiotemporal Asset“ sind alle Dokumente gemeint, die Information mit Raum- und Zeitbezug über die Erde repräsentieren. Momentan sind dies hauptsächlich Fernerkundungsaufnahmen (Satellit, Flugz
Einige der Erweiterungen bestehen bereits, bspw. SAR und Point Clouds. Einige bisher Zukunftspläne (Full Motion Video, ...). Da wäre eine Unterscheidung wichtig, damit klar wird was bereits geht und was noch nicht.

Es ist nicht korrekt, dass STAC nicht mit Vektordaten arbeitet.

2020-10-29 15:19 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +Weitere Infos: [Website STAC](https://stacspec.org/), [Video Vorstellung STAC](http://bofh.nikhef.nl/events/FOSDEM/2020/AW1.126/introduction_to_spatiotemporal_asset_catalogs_stac.mp4)
Hier eine etwas aktuelle STAC Vorstellung:
https://www.youtube.com/watch?v=qGRrDPTwpmk

Zudem gibt es einige weitere Videos mit STAC Bezug in dieser YouTube Playlist: https://www.youtube.com/watch?v=wtCqkhLS_AM&list=PL3QzFgBMGnbQWbW-V09AzSfCbnf6Q87Rq

2020-10-29 15:21 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +STAC nutzt das JSON-Format. Das Kern GeoJSON-Objekt kann erweitert werden um es für verschiedene Domänen anzupassen. Die JSON-Seiten können in interaktive HTML-Seiten umgewandelt werden.
Nur die STAC Items sind GeoJSON-Dateien.

Womit ist eine Umwandlung in HTML-Seiten möglich?

2020-10-29 15:24 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +- **STAC Item**: einzelnes Spatiotemporal Asset
Ein Item ist eine Gruppierung von Assets, die normalerweise sehr ähnliche Eigenschaften besitzen (bspw. ein Foto [=Item] bei dem jedes spektrales Band in einer eigenen Datei [=Asset] vorliegt).

2020-10-29 15:25 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +Als GeoJSON hat das STAC Item Felder für id, type, bbox, geometry und properties. Das STAC Item hat zusätzliche Felder für ein Thumbnail, Asset Links zu Daten, Relationship Links zu verwandten STAC I
Vllt noch zu erwähnen ist, dass viele wichtige Metadaten im properties Feld untergebracht sind.

2020-10-29 15:26 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +Bei dem STAC Catalog handelt es sich um eine JSON-Datei mit einer Liste von STAC Items und/oder eine Liste von Sub-Catalogs, wodurch eine hierarchische Anordnung von STAC Items möglich ist. STAC Cata
Ein Catalog enthält eine Liste _an Links_ zu STAC Items, nicht die STAC Items selber.

2020-10-29 15:28 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +| Endpoint                                        | Returns        | Description |
Quelle?

2020-10-29 15:30 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +### STAC API
Wo findet man STAC APIs?

2020-10-29 15:30 UTC, m-mohr commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +### STAC Catalog
Wo findet man bestehende STAC Kataloge?

2020-10-30 21:02 UTC, digilog11 commented on stac:-the-spatiotemporal-asset-catalogue/handout.md
> +## Gründe für die Entwicklung von STAC
Ich habe keine Online-Ressource finden können, die STAC mit OGC Standards vergleicht. Idealerweise hätte ich zu so etwas verlinkt, da das Handout (und Referat) schon recht lang sind. Da ich mich mit CSW, W(C)PS nicht wirklich auskenne, finde ich es auch schwierig, das eigenständig auszuarbeiten.  
Ich habe nur einige Gründe finden können, die STAC gegenüber CSW, W(C)PS etc. geeigneter macht:
-  OGC Standards sind komplex, STAC ist simpler und verständlicher für Einsteiger/Nicht-GI-Experten
-  STAC bietet einen statischen Katalog, während OGC Standards als APIs implementiert werden (STAC geringere Schwelle zur Veröffentlichung eines Katalogs, STAC crawlable)
-  OGC eher auf XML ausgerichtet, STAC hingegen auf lesefreundlicheres JSON

Gibt es andere Erklärungen, warum CSW, W(C)PS nicht geeignet sind?

2020-11-04 14:59 UTC, digilog11 commented
Zur Frage aus dem Kurs:

Aus der STAC Spezifikation:
"The division of sub-catalogs is up to the implementor, but is generally done to aid the ease of online browsing by people. [...] Any use that is publishing a set of related spatiotemporal assets is strongly recommended to also use the STAC Collection specification to provide additional information. [...] STAC Collections further define and explain logical groups of Items."

Es wird nicht näher darauf eingegangen, was related Items/logical groups of Items sind. Ich denke, das kann der Data Provider für sich entscheiden.

2020-11-19 13:57 UTC, nuest commented
@digilog11 ich würde mich freuen, wenn du die offenen Kommentare noch nacharbeitest, ich merge aber dennoch erstmal, weil die Bewertung jetzt auch abgeschlossen ist.

2020-11-19 13:57 UTC, merged