handout openEO - Processes, Backend and Platform
Geosoft2/geosoft2-2020 pull request #21
Opened 2020-10-28 14:15 UTC by jana2308walter

@jana2308walter

Handout bereit für Feedback

2020-10-29 10:20 UTC, nuest requested changes
Es fehlen **Quellen und Links** - am besten direkt im Text. Die Inhalte hier sollen bewerten und zusammenfassen, müssen nicht alle Details beinhalten.

Hast du mit @FelixGI1516 gesprochen?

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +#### Vorteile:
Für bessere Lesbarkeit: keine `:` bei Überschriften, eine Leerzeile vor und nach Überschriften.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +openEO ist eine offene API, die R, Python, JavaScript u. a. auf einheitliche Weise mit Backends zur Erdbeobachtung verbindet
Die Backends sind nicht zur Erdbeobachtung - bitte präziser Formulieren.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +* open: Open Source Software in Form von source code, die modifiziert und verändert werden kann
nicht nur die Software ist open, auch die API-Spezifikation - gerne auch verlinken und die Lizenzen erwähnen.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +#### Ziele des Projektes:
Quelle?

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +Daten werden in der Cloud und in Backends gespeichert und verarbeitet, dann können die Ergebnisse heruntergeladen werden
wichtig: offene API!

Der Vergleich mit GDAL hilft mir ja immer das zu erklären - kennst Du das?

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +Beispieldatei: [ceil.json] (https://github.com/Open-EO/openeo-processes/blob/master/ceil.json)
Linkformatierung korrigieren.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +## Prozesse
Hast du mal den client ausprobiert und einen Prozess erstellt und ausgeführt? Wenn nicht, dann bitte machen und von deinen praktischen Erfahrungen berichten!

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +## Backends:
Links fehlen zu den Backend-Projekten aber auch zu den Softwareprojekten/Produkten, die durch die Backends angebunden werden.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +#### Welche Verarbeitungsplattformen?
Links!

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +
Wie sieht es mit Datenmengen aus, also Beispielgrößen - nur damit man sich das besser vorstellen kann.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +Um einen eigenen Backend – Treiber zu starten, sollte man mit den gemeinsamen Funktionalitäten, die in einigen Programmiersprachen (z. B.: Java (Spring) API Commons, Python API Commons) implementiert
Es gibt auch noch die client-Softwareprojekte - bitte ergänzen.

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +#### Machine Learning (ML) und künstliche Intelligenz (KI)
Links!

Welche Bibliotheken werden eingebunden?

2020-10-29 10:20 UTC, nuest commented on handout-openeo-backend-processes-platform/handout.md
> +* Softwareentwickler können in eigener DIE arbeiten, um Dienste in Anwendungen zu integrieren
Meinst du "IDE" ?

2020-10-29 12:13 UTC, jana2308walter commented
Vielen Dank für das ausführliche Feedback, ich habe mich bemüht dies umzusetzen, leider ist es mir nicht möglich, die eingebundenen Bibliotheken und die Beispielgrößen zu finden. 
Das Ausprobieren des Clients und die Verlinkung der Clients und der API fällt doch eher in Felix Bereich oder habe ich das missverstanden?

2020-10-29 15:03 UTC, m-mohr commented on handout-openeo-backend-processes-platform/handout.md
> +* Gegründet von der ESA, gestartet in September 2020
Finanziert von der ESA

2020-10-29 15:10 UTC, m-mohr commented on handout-openeo-backend-processes-platform/handout.md
> +Einige Beispiele hierfür sind:
Provider können Google Earth Engine und Sentinel Hub praktisch nicht selbst hosten, da die Infrastrukturen von diesen Betreibern proprietär sind. Die openEO-Implementierungen sind zwar verfügbar, aber es bringt Providern diese zu nutzen, da sie keine eigenen Daten einspeisen können.

2020-10-29 15:10 UTC, m-mohr commented on handout-openeo-backend-processes-platform/handout.md
> +## Prozesse
Sollte es an Zugangsdaten mangeln, mich hier kurz anpingen...

2020-10-29 21:25 UTC, jana2308walter commented
Ok danke, ich habe es noch einmal upgedated!

2020-11-15 13:44 UTC, jana2308walter commented on handout-openeo-backend-processes-platform/handout.md
> +## Prozesse
Hallo @m-mohr , 

wir versuchen gerade noch einmal die API zu testen und bräuchten Zugangsdaten für das Backend der Google Earth Engine, können Sie uns dabei weiterhelfen?

2020-11-15 16:26 UTC, m-mohr commented on handout-openeo-backend-processes-platform/handout.md
> +## Prozesse
Hallo, ich habe euch die Daten in Mattermost zur Verfügung gestellt.

2020-11-19 13:59 UTC, merged