Fermazin TileDB
Geosoft2/geosoft2-2020 pull request #24
Opened 2020-11-01 11:55 UTC by Fmazin

Das TileDB Handout von @FMazin mit einigen ergänzenden Grafiken.

2020-11-03 11:03 UTC, nuest requested changes
Inhaltlich erstmal in die richtige Richtung, aber: hast du das praktisch getestet? Wie sind deine Erfahrungen dazu?

2020-11-03 11:03 UTC, nuest commented on tiledb/@Fmazin-handout.md
> +The above mentioned attributes of TileDB make it in the words of the developers a universal data Engine. Broken down this means: 'It can store almost anything and you can access it through almost any
Leere Zeilen vor und nach Überschriften erhöht die Lesbarkeit als plain text.

2020-11-03 11:03 UTC, nuest commented on tiledb/@Fmazin-handout.md
> +#### 3. 2. 2. Additional Sources
Kommt hier noch was?

2020-11-04 09:18 UTC, Fmazin commented on tiledb/@Fmazin-handout.md
> +The above mentioned attributes of TileDB make it in the words of the developers a universal data Engine. Broken down this means: 'It can store almost anything and you can access it through almost any
Abstand nach überschriften eingefügt.

2020-11-19 14:02 UTC, merged